/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.FileNotFoundException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.stream.XMLStreamException;
import main.Course;
import main.Dom_Parser;
import main.StAX_Iterator_Parser;
import main.Student;
import main.Students;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    Vector vctHeader;
    Vector vctData;
    Students students = new Students();
    StAX_Iterator_Parser stAXIterator = new StAX_Iterator_Parser();
    Student student;
    Dom_Parser domParser = new Dom_Parser();
    boolean updateStudent = false, mouseClick = false;

    /**
     * Creates new form mainFrame
     */
    public MainFrame() {
        initComponents();
        vctHeader = new Vector();
        vctHeader.add("Roll");
        vctHeader.add("Name");
        vctHeader.add("Phone");
        vctHeader.add("Email");
        vctHeader.add("Course Code");
        vctHeader.add("Course Name");
        vctHeader.add("Credit");
        vctHeader.add("Score");
        load();
    }

    public void load() {
        stAXIterator = new StAX_Iterator_Parser();
        students = new Students();
        vctData = new Vector();
        stAXIterator.parseFile("student.xml");
        students = stAXIterator.getStudents();
        for (Student student : students) {
            Vector row = new Vector();
            row.add(student.getId());
            row.add(student.getName());
            row.add(student.getPhone());
            row.add(student.getEmail());
            row.add(student.getCourse().getCourseCode());
            row.add(student.getCourse().getCourseName());
            row.add(student.getCredit());
            row.add(student.getScore());
            vctData.add(row);
            tblStudent.setModel(new DefaultTableModel(vctData, vctHeader));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogFrame = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        txtCourseCode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCredit = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtScore = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lbPhone = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        lbCode = new javax.swing.JLabel();
        lbScore = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbCourse = new javax.swing.JLabel();
        lbCredit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        btnAddNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        dialogFrame.setAutoRequestFocus(false);
        dialogFrame.setLocation(new java.awt.Point(600, 300));
        dialogFrame.setMinimumSize(new java.awt.Dimension(845, 450));
        dialogFrame.setResizable(false);

        jLabel12.setText("Course");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel13.setText("Credit");
        jLabel13.setToolTipText("");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel14.setText("Score");
        jLabel14.setToolTipText("");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 102));
        jLabel15.setText("Detail Information");

        jLabel16.setText("Course Name");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel17.setText("Student_ID");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel18.setText("Student_Name");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtName.setMaximumSize(new java.awt.Dimension(6, 20));

        jLabel19.setText("Phone");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtPhone.setMaximumSize(new java.awt.Dimension(6, 20));

        lbPhone.setForeground(new java.awt.Color(255, 0, 51));
        lbPhone.setMaximumSize(new java.awt.Dimension(150, 0));
        lbPhone.setMinimumSize(new java.awt.Dimension(150, 0));
        lbPhone.setPreferredSize(new java.awt.Dimension(150, 0));

        jLabel20.setText("Email");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtEmail.setMaximumSize(new java.awt.Dimension(6, 20));

        lbEmail.setForeground(new java.awt.Color(255, 0, 51));
        lbEmail.setMaximumSize(new java.awt.Dimension(150, 0));
        lbEmail.setMinimumSize(new java.awt.Dimension(150, 0));
        lbEmail.setPreferredSize(new java.awt.Dimension(150, 0));

        lbCode.setForeground(new java.awt.Color(255, 0, 51));
        lbCode.setLabelFor(lbCode);
        lbCode.setMaximumSize(new java.awt.Dimension(150, 0));
        lbCode.setMinimumSize(new java.awt.Dimension(150, 0));
        lbCode.setPreferredSize(new java.awt.Dimension(150, 0));

        lbScore.setForeground(new java.awt.Color(255, 0, 51));
        lbScore.setMaximumSize(new java.awt.Dimension(150, 0));
        lbScore.setMinimumSize(new java.awt.Dimension(150, 0));
        lbScore.setPreferredSize(new java.awt.Dimension(150, 0));

        lbName.setForeground(new java.awt.Color(255, 0, 51));
        lbName.setMaximumSize(new java.awt.Dimension(150, 0));
        lbName.setMinimumSize(new java.awt.Dimension(150, 0));
        lbName.setPreferredSize(new java.awt.Dimension(150, 0));

        lbCourse.setForeground(new java.awt.Color(255, 0, 51));
        lbCourse.setMaximumSize(new java.awt.Dimension(150, 0));
        lbCourse.setMinimumSize(new java.awt.Dimension(150, 0));
        lbCourse.setPreferredSize(new java.awt.Dimension(150, 0));

        lbCredit.setForeground(new java.awt.Color(255, 0, 51));
        lbCredit.setMaximumSize(new java.awt.Dimension(150, 0));
        lbCredit.setMinimumSize(new java.awt.Dimension(150, 0));
        lbCredit.setPreferredSize(new java.awt.Dimension(150, 0));

        javax.swing.GroupLayout dialogFrameLayout = new javax.swing.GroupLayout(dialogFrame.getContentPane());
        dialogFrame.getContentPane().setLayout(dialogFrameLayout);
        dialogFrameLayout.setHorizontalGroup(
            dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogFrameLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(dialogFrameLayout.createSequentialGroup()
                        .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(dialogFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(87, 87, 87))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(dialogFrameLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(88, 88, 88)))
                        .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dialogFrameLayout.createSequentialGroup()
                                .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCourseName))
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCode)
                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtScore)
                            .addComponent(txtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSave)
                        .addGroup(dialogFrameLayout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(370, 370, 370))))
                .addGap(18, 18, 18)
                .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCredit, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        dialogFrameLayout.setVerticalGroup(
            dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogFrameLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel12))
                    .addGroup(dialogFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dialogFrameLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbScore, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Search By ID:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblStudent.setEditingColumn(0);
        tblStudent.setEditingRow(0);
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudent);

        btnAddNew.setText("Add New");
        btnAddNew.setMaximumSize(new java.awt.Dimension(75, 3));
        btnAddNew.setMinimumSize(new java.awt.Dimension(75, 33));
        btnAddNew.setPreferredSize(new java.awt.Dimension(75, 33));
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.setMinimumSize(new java.awt.Dimension(75, 33));
        btnUpdate.setPreferredSize(new java.awt.Dimension(75, 33));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setMinimumSize(new java.awt.Dimension(75, 33));
        btnDelete.setPreferredSize(new java.awt.Dimension(75, 33));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.setMaximumSize(new java.awt.Dimension(75, 33));
        btnExit.setMinimumSize(new java.awt.Dimension(75, 33));
        btnExit.setPreferredSize(new java.awt.Dimension(75, 33));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("STUDENT MANAGEMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(256, 256, 256))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        txtSearch.getAccessibleContext().setAccessibleName("txtSearch");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        updateStudent = false;
        txtCode.setText("");
        txtName.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtCourseCode.setText("");
        txtCourseName.setText("");
        txtCredit.setText("");
        txtScore.setText("");
        clearLabel();
        dialogFrame.setVisible(true);
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (!mouseClick) {
            JOptionPane.showMessageDialog(this, "Choose 1 student for updating");
        } else {
            updateStudent = true;
            dialogFrame.setVisible(true);
            updateStudent(student);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (!mouseClick) {
            JOptionPane.showMessageDialog(this, "Choose 1 student for deleting");
        } else {
            for (int i = 0; i < students.size(); i++) {
                if (student.getId().equalsIgnoreCase(students.get(i).getId())) {
                    students.remove(i);
                }
            }
            try {
                domParser.updateFile(students, "student.xml");
            } catch (ParserConfigurationException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            mouseClick = false;
            JOptionPane.showMessageDialog(this, "XML file update successfully");
            load();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
        // TODO add your handling code here:
        int index = tblStudent.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();

        String id = model.getValueAt(index, 0).toString();
        String name = model.getValueAt(index, 1).toString();
        String phone = model.getValueAt(index, 2).toString();
        String email = model.getValueAt(index, 3).toString();
        String courseCode = model.getValueAt(index, 4).toString();
        String courseName = model.getValueAt(index, 5).toString();
        int credit = Integer.parseInt(model.getValueAt(index, 6).toString());
        int score = Integer.parseInt(model.getValueAt(index, 7).toString());

        Course course = new Course(courseCode, courseName);
        student = new Student(id, name, phone, email, course, credit, score);
        mouseClick = true;
    }//GEN-LAST:event_tblStudentMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        if (!updateStudent) {
            String id = txtCode.getText();
            String name = txtName.getText();
            String phone = txtPhone.getText();
            String email = txtEmail.getText();
            String courseName = txtCourseName.getText();
            String courseCode = txtCourseCode.getText().toUpperCase();

            if (!txtCredit.getText().matches("^[0-9]{1,2}$")) {
                lbCredit.setText("Credit is number");
            } else {
                lbCredit.setText(null);
            }
            int credit = Integer.parseInt(txtCredit.getText());

            if (!txtScore.getText().matches("^[0-9]{1,2}$")) {
                lbScore.setText("Score is number");
            } else {
                lbScore.setText(null);
            }
            int score = Integer.parseInt(txtScore.getText());

            Course course = new Course(courseCode, courseName);
            student = new Student(id, name, phone, email, course, credit, score);

        } else {
            for (int i = 0; i < students.size(); i++) {
                if (student.getId().equalsIgnoreCase(students.get(i).getId())) {
                    students.get(i).setName(txtName.getText());
                    students.get(i).setPhone(txtPhone.getText());
                    students.get(i).setEmail(txtEmail.getText());
                    String courseCode = txtCourseCode.getText().toUpperCase();
                    String courseName = txtCourseName.getText();
                    students.get(i).setCourse(new Course(courseCode, courseName));
                    students.get(i).setCredit(Integer.parseInt(txtCredit.getText()));
                    students.get(i).setScore(Integer.parseInt(txtScore.getText()));
                }
            }
        }

        if (validate(student)) {
            if (!updateStudent) {
                students.add(student);
            }
            try {
                domParser.updateFile(students, "student.xml");
            } catch (ParserConfigurationException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            clearLabel();
            mouseClick = false;
            dialogFrame.setVisible(false);
            JOptionPane.showMessageDialog(this, "XML file update successfully");
            load();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    public void clearLabel() {
        lbCode.setText(null);
        lbCourse.setText(null);
        lbName.setText(null);
        lbCredit.setText(null);
        lbEmail.setText(null);
        lbPhone.setText(null);
        lbScore.setText(null);
    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String id = txtSearch.getText().toUpperCase();        
        int index = 0;
        for (int i = 0; i < students.size(); i++) {
            if (students.get(i).getId().equalsIgnoreCase(id)) {
                index = i;
            }
        }
        tblStudent.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_btnSearchActionPerformed

    public boolean validate(Student student) {

        //validateID
        if (student.getId() == null) {
            lbCode.setText("ID can't be empty.");
            return false;
        } else if (!student.getId().matches("^SE[0-9]{5}")) {
            this.txtCode.requestFocus();
            lbCode.setText("Wrong formatt ID [SE00000]");
            return false;
        } else if (!updateStudent) {
            for (int i = 0; i < students.size(); i++) {
                if (student.getId().equalsIgnoreCase(students.get(i).getId())) {
                    this.txtCode.requestFocus();
                    lbCode.setText("This ID already existed");
                    return false;
                } else {
                    lbCode.setText(null);
                }
            }
        } else {
            lbCode.setText(null);
        }

        //validate Name
        if (student.getName().length() < 5 || student.getName().length() > 30) {
            this.txtName.requestFocus();
            lbName.setText("Name has length from 5 to 30 "
                    + "\n" + "characters.");
            return false;
        } else if (student.getName().matches("/d")) {
            this.txtName.requestFocus();
            lbName.setText("Name only contains characters.");
            return false;
        } else {
            lbName.setText(null);
        }

        //validate phone
        if (student.getPhone().length() != 10) {
            this.txtPhone.requestFocus();
            lbPhone.setText("Phone must have 10 numbers");
            return false;
        } else if (!student.getPhone().matches("[0-9]{10}")) {
            this.txtPhone.requestFocus();
            lbPhone.setText("Phone must have 10 numbers");
            return false;
        } else {
            lbPhone.setText(null);
        }

        //validate email
        if (!student.getEmail().matches("^(.+)@(.+).(.+)$")) {
            this.txtEmail.requestFocus();
            lbEmail.setText("Email has formatt [aaa@aaa.aaa]");
            return false;
        } else {
            lbEmail.setText(null);
        }

        //validate courseCode
        if (!student.getCourse().getCourseCode().matches("^[A-Z]{3}+[0-9]{3}$")) {
            this.txtCourseCode.requestFocus();
            lbCourse.setText("Wrong formatt. Course Code has formatt [XXX000]");
            return false;
        } else {
            lbCourse.setText(null);
        }
        return true;
    }

    public void updateStudent(Student student) {
        txtCode.setText(student.getId());
        txtCode.setEditable(false);
        txtName.setText(student.getName());
        txtPhone.setText(student.getPhone());
        txtEmail.setText(student.getEmail());
        txtCourseCode.setText(student.getCourse().getCourseCode());
        txtCourseName.setText(student.getCourse().getCourseName());
        txtCredit.setText(String.valueOf(student.getCredit()));
        txtScore.setText(String.valueOf(student.getScore()));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JDialog dialogFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCode;
    private javax.swing.JLabel lbCourse;
    private javax.swing.JLabel lbCredit;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbScore;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCourseCode;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCredit;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtScore;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
